//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorGameApp.WindowsForm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Akcja")]
        public string actionString {
            get {
                return ((string)(this["actionString"]));
            }
            set {
                this["actionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Start")]
        public string startString {
            get {
                return ((string)(this["startString"]));
            }
            set {
                this["startString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resetuj aplikację")]
        public string resetAppString {
            get {
                return ((string)(this["resetAppString"]));
            }
            set {
                this["resetAppString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Zamknij")]
        public string closeString {
            get {
                return ((string)(this["closeString"]));
            }
            set {
                this["closeString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poziom trudności")]
        public string levelString {
            get {
                return ((string)(this["levelString"]));
            }
            set {
                this["levelString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poziom brązowy: czas rundy -> 2 sekundy")]
        public string level1String {
            get {
                return ((string)(this["level1String"]));
            }
            set {
                this["level1String"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poziom srebrny: czas rundy -> 1,5 sekundy")]
        public string level2String {
            get {
                return ((string)(this["level2String"]));
            }
            set {
                this["level2String"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Poziom złoty: czas rundy -> 1 sekunda")]
        public string level3String {
            get {
                return ((string)(this["level3String"]));
            }
            set {
                this["level3String"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Informacje")]
        public string infoString {
            get {
                return ((string)(this["infoString"]));
            }
            set {
                this["infoString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wybierz kolor:")]
        public string chooseColorString {
            get {
                return ((string)(this["chooseColorString"]));
            }
            set {
                this["chooseColorString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pozostały czas:")]
        public string remainingTimeString {
            get {
                return ((string)(this["remainingTimeString"]));
            }
            set {
                this["remainingTimeString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Punkty:")]
        public string pointsString {
            get {
                return ((string)(this["pointsString"]));
            }
            set {
                this["pointsString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aby zagrać, naciśnij Start.")]
        public string startInfoString {
            get {
                return ((string)(this["startInfoString"]));
            }
            set {
                this["startInfoString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test na kolory")]
        public string colorGameTitleString {
            get {
                return ((string)(this["colorGameTitleString"]));
            }
            set {
                this["colorGameTitleString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Informacje")]
        public string alertInfoTitleString {
            get {
                return ((string)(this["alertInfoTitleString"]));
            }
            set {
                this["alertInfoTitleString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Autorem gry jest Łukasz Krzos. Aby zagrać w grę należy wybrać opcję [Start] z men" +
            "u.")]
        public string alertInfoContentString {
            get {
                return ((string)(this["alertInfoContentString"]));
            }
            set {
                this["alertInfoContentString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wynik gry")]
        public string alertGameOverTitleString {
            get {
                return ((string)(this["alertGameOverTitleString"]));
            }
            set {
                this["alertGameOverTitleString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Uzyskałeś")]
        public string alertGameOverContent1String {
            get {
                return ((string)(this["alertGameOverContent1String"]));
            }
            set {
                this["alertGameOverContent1String"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("punktów")]
        public string alertGameOverContent2String {
            get {
                return ((string)(this["alertGameOverContent2String"]));
            }
            set {
                this["alertGameOverContent2String"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Koniec gry")]
        public string menuStripGameOverString {
            get {
                return ((string)(this["menuStripGameOverString"]));
            }
            set {
                this["menuStripGameOverString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Potwierdzenie")]
        public string alertExitTitleString {
            get {
                return ((string)(this["alertExitTitleString"]));
            }
            set {
                this["alertExitTitleString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Czy na pewno chcesz wyjść?")]
        public string alertExitContentString {
            get {
                return ((string)(this["alertExitContentString"]));
            }
            set {
                this["alertExitContentString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sek.")]
        public string secondsString {
            get {
                return ((string)(this["secondsString"]));
            }
            set {
                this["secondsString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test na kolory")]
        public string titleString {
            get {
                return ((string)(this["titleString"]));
            }
            set {
                this["titleString"] = value;
            }
        }
    }
}
